### ISSUE TITLE
Font Improvement

### ISSUE THREAD

**Issue by zicklag** [fishfolk/fishfolk.org#10]
_Originally opened in #8_

The current font is hard to read or look at in certain parts of the site. We should pick one or more other fonts we can use where the font doesn't work well.

One area of specific note is the search bar.

**Comment by KacperM45440** [comment]
![image](https://user-images.githubusercontent.com/104095161/224192565-36322dad-6d16-4736-9323-c5dcfb877955.png)

Used a sans-serif styled font for the header and footer - I'd say they look pretty neat!
The font's called "Nunito Sans" and can be found on Google Fonts.

**Comment by zicklag** [comment]
Yeah, I think that looks pretty nice. 👍 And it goes well with the sun and github icons we're using.

I'll update the site to use that once I get to this, thanks!
